<?php
/**
 * @file
 * @see https://api.drupal.org/api/drupal/core!core.api.php/group/hooks/
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * @description Implements hook_help()
 * @see https://api.drupal.org/api/drupal/core!modules!help!help.api.php/function/hook_help/
 *
 * @param string $route_name
 * @param RouteMatchInterface $route_match
 * @return string|void
 */
function MACHINE_NAME_help(string $route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    case 'help.page.MACHINE_NAME':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is the help page for ADMIN_NAME') . '</p>';

      return $output;

    default:
  }
}

/**
 * @description Implements hook_form_alter()
 * @see https://api.drupal.org/api/drupal/core!lib!Drupal!Core!Form!form.api.php/function/hook_form_alter/
 *
 * @param array $form
 * @param FormStateInterface $form_state
 * @param string $form_id
 * @return void
 */
function MACHINE_NAME_form_alter(array &$form, FormStateInterface $form_state, $form_id) {}

/**
 * @description Implements hook_cron()
 * @see https://api.drupal.org/api/drupal/core%21core.api.php/function/hook_cron
 *
 * @return void
 */
function MACHINE_NAME_cron() {}

/**
 * @description Implements hook_page_attachments()
 * @see https://api.drupal.org/api/drupal/core!lib!Drupal!Core!Render!theme.api.php/function/hook_page_attachments/
 *
 * @param array $attachments
 * @return void
 */
function MACHINE_NAME_page_attachments(array &$attachments) {}
