<?php
/**
 * @file
 *
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * @description Implements hook_help()
 * @see https://api.drupal.org/api/drupal/core!modules!help!help.api.php/function/hook_help/
 *
 * @param string $route_name
 * @param RouteMatchInterface $route_match
 * @return string|void
 */
function MACHINE_NAME_help(string $route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    case 'help.page.MACHINE_NAME':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is the help page for ADMIN_NAME') . '</p>';

      return $output;

    default:
  }
}

/**
 * @description Implements hook_preprocess_node()
 * @see https://api.drupal.org/api/drupal/core!modules!node!node.module/function/template_preprocess_node
 *
 * @return void
 */
function MACHINE_NAME_preprocess_node(&$vars) {}
